openapi: 3.0.3
info:
  title: CyberVault API
  description: REST API specification for CyberVault backend.
  version: 0.1.0
servers:
  - url: http://localhost:4000/api/v1
paths:
  /auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [Admin, Manager, User]
      responses:
        '201':
          description: User created 